AllCops:
  Exclude:
    - 'lab/**/*'
    
Layout/EndOfLine:
  Enabled: false # Make source portable!

Metrics/AbcSize:
  Max: 22 

Metrics/ClassLength:
  Max: 150
  
Metrics/CyclomaticComplexity:
  Max: 10   

Metrics/MethodLength:
  Max: 50
  
Metrics/PerceivedComplexity:
  Max: 10  

Naming/MethodParameterName:
  Enabled: false
  
Naming/VariableName:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false  