module Sequitur
  # In linguistics, a digram is a sequence of two letters.
  # In Sequitur, a digram is a sequence of two consecutive symbols that
  # appear in a production rule. Each symbol in a digram
  # can be a terminal or not.
  class Digram
    # The sequence of two consecutive grammar symbols.
    # @return [Array<String, Symbol>] The two symbols should respond to the :hash message.
    attr_reader symbols: Array<String|Symbol>

    # @return [String] An unique hash key of the digram
    attr_reader key: String

    # @return [Sequitur::Production] The production in which the digram occurs
    attr_reader production: Sequitur::Production

    # Constructor.
    # A digram represents a sequence of two symbols
    # (that appears in a rhs of a production).
    # Terminal symbols must respond to the :hash message.
    # @param symbol1 [String, Symbol] First element of the digram
    # @param symbol2 [String, Symbol] Second element of the digram
    # @param aProduction [Sequitur::Production] Production in which the RHS
    #   the sequence symbol1 symbol2 appears.
    def initialize: ((String | Symbol) symbol1, (String | Symbol) symbol2, Sequitur::Production aProduction) -> void

    # Equality testing.
    #   true iff keys of both digrams are equal, false otherwise
    # @param other [Sequitur::Digram] another to compare with
    # @return [TrueClass, FalseClass]
    def ==: (Sequitur::Digram other) -> bool

    # Does the digram consists of twice the same symbols?
    # @return [TrueClass, FalseClass] true when symbols.first == symbols.last
    def repeating?: () -> bool
  end
end
